### ISSUE TITLE
快速上手第一步，CapsuleManager镜像获得失败

### ISSUE THREAD

**Issue by Zengm2008** [secretflow/trustedflow#12]
docker run -it secretflow/capsule-manager-sim:latest
Unable to find image 'secretflow/capsule-manager-sim:latest' locally
docker: Error response from daemon: manifest for secretflow/capsule-manager-sim:latest not found: manifest unknown: manifest unknown.
docker pull secretflow/capsule-manager-sim:latest
Error response from daemon: manifest for secretflow/capsule-manager-sim:latest not found: manifest unknown: manifest unknown

**Comment by zhouaihui** [comment]
抱歉，仓库里的文档已经更新了，官网文档没有及时同步。

解决办法：
1. 方法一：您可以再重试一下，latest镜像已经推送了。
2. 方法二：使用我们最新的文档，可以阅读 https://github.com/secretflow/trustedflow/blob/main/docs/quick_start/step1.ipynb，有最新的镜像名称。

官网稍后会同步。

**Comment by zhouaihui** [comment]
官网已经更新，您可以阅读官网获得最新的文档信息。
