### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by zhouyou9505** [secretflow/trustedflow#16]
### 问题描述

cms_config init --host {CapsuleManager的服务地址} --sim true --root-ca-file xxx --private-key-file alice.key --cert-chain-file alice.crt --root-ca-file alice_ca.crt

--root-ca-file 写重复了

### 技术信息

- 页面 https://www.secretflow.org.cn/docs/trustedflow/main/zh-Hans/quick_start/step2
- 源码 https://github.com/secretflow/trustedflow/blob/e529736dda5000fa638150b0c1992a603de524ba/docs/quick_start/step2.ipynb
- 浏览器 `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`

**Comment by zhouaihui** [comment]
hi, @zhouyou9505 , 感谢提出问题，你可以提一个PR帮忙修复该问题吗？
