### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by zhouyou9505** [secretflow/trustedflow#19]
### 问题描述
执行会报错
cms_util generate-party-id --cert-pems-file alice.crt

Usage: cms_util generate-party-id [OPTIONS]
Try 'cms_util generate-party-id --help' for help.

Error: No such option: --cert-pems-file Did you mean --cert-file?

改为 cms_util generate-party-id --cert-file alice.crt

### 技术信息

- 页面 https://www.secretflow.org.cn/docs/trustedflow/main/zh-Hans/quick_start/step2
- 源码 https://github.com/secretflow/trustedflow/blob/96b7be5db10d5d8b84d7106e65eae5a3d358b64a/docs/quick_start/step2.ipynb
- 浏览器 `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`

**Comment by Chrisdehe** [comment]
与[#10](https://github.com/secretflow/capsule-manager-sdk/issues/10)同样的问题，修复后会在此issue中反馈。
cc @yuki252111

**Comment by yuki252111** [comment]
已修复，感谢反馈
