### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by PrimumMobile** [secretflow/trustedflow#27]
### 文档修改建议

<details>
      <summary>技术信息</summary>
      <ul>
        <li>页面 <a href="https://www.secretflow.org.cn/zh-CN/docs/trustedflow/main/quick_start/step3">https://www.secretflow.org.cn/zh-CN/docs/trustedflow/main/quick_start/step3</a></li>
        <li>源码 <a href="https://github.com/secretflow/trustedflow/blob/47d96c25b320d6c2faae3332aed4d1b83b6b9872/docs/quick_start/step3.ipynb">https://github.com/secretflow/trustedflow/blob/47d96c25b320d6c2faae3332aed4d1b83b6b9872/docs/quick_start/step3.ipynb</a></li>
        <li>浏览器 <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0</code></li>
      </ul>
    </details>
OP_PSI 隐私求交

**Comment by Chrisdehe** [comment]
hey，非常感谢你的发现，这是一个文档翻译的问题，我们会排期修复。

另外如果需要进一步沟通可以联系：
技术支持WeChat：secretflow02
