### ISSUE TITLE
trustedflow快速上手步骤一：（仅carol）前置部署

### ISSUE THREAD

**Issue by qinjuana** [secretflow/trustedflow#31]
### 文档修改建议
请明确启动

假设三方机构bob alice，carol，每个机构分别部署在一个虚机上，各虚机间可正常通信。
每个机构已经生成一个自签的证书和私钥。
carol部署CapsuleManager时，如下：
CapsuleManager 默认会启用mTLS，关于如何配置mTLS可以参考[CapsuleManager mTLS](https://github.com/secretflow/capsule-manager/blob/master/README.md#mutual-tls)：
./capsule_manager --server-cert-key-path <SERVER_CERT_KEY_PATH> \
                  --server-cert-path <SERVER_CERT_PATH>         \
                  --client-ca-cert-path <CLIENT_CA_CERT_PATH>
这里面的server-cert-key，-server-cert-path及client-ca-cert-path路径如何确定？server-cert和client-ca-cert分别指什么？与机构生成的自签证书是一回事吗？

<details>
      <summary>技术信息</summary>
      <ul>
        <li>页面 <a href="https://www.secretflow.org.cn/zh-CN/docs/trustedflow/main/quick_start/step1">https://www.secretflow.org.cn/zh-CN/docs/trustedflow/main/quick_start/step1</a></li>
        <li>源码 <a href="https://github.com/secretflow/trustedflow/blob/47d96c25b320d6c2faae3332aed4d1b83b6b9872/docs/quick_start/step1.ipynb">https://github.com/secretflow/trustedflow/blob/47d96c25b320d6c2faae3332aed4d1b83b6b9872/docs/quick_start/step1.ipynb</a></li>
        <li>浏览器 <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36</code></li>
      </ul>
    </details>

**Comment by zhongtianq** [comment]
我们即将发布一版，会有一些流程和文档优化。
关于证书，机构自签证书在https://www.secretflow.org.cn/zh-CN/docs/trustedflow/main/quick_start说明了如何生成。
CapsuleManager 的server-cert-key，-server-cert-path及client-ca-cert-path都是指tls相关的内容，与自签证书无关。
server-cert-key指CapsuleManager的TLS私钥路径，server-cert-path为CA为CapsuleManager签发的TLS证书，client-ca-cert-path代表为客户端签发TLS证书的权威CA的证书，用于认证client的身份。
这些命名在下一版文档里面也会重新命名，也会有补充相关说明。

**Comment by zhongtianq** [comment]
> 我们即将发布一版，会有一些流程和文档优化。 关于证书，机构自签证书在[https://www.secretflow.org.cn/zh-CN/docs/trustedflow/main/quick_start说明了如何生成。](https://www.secretflow.org.cn/zh-CN/docs/trustedflow/main/quick_start%E8%AF%B4%E6%98%8E%E4%BA%86%E5%A6%82%E4%BD%95%E7%94%9F%E6%88%90%E3%80%82) CapsuleManager 的server-cert-key，-server-cert-path及client-ca-cert-path都是指tls相关的内容，与自签证书无关。 server-cert-key指CapsuleManager的TLS私钥路径，server-cert-path为CA为CapsuleManager签发的TLS证书，client-ca-cert-path代表为客户端签发TLS证书的权威CA的证书，用于认证client的身份。 这些命名在下一版文档里面也会重新命名，也会有补充相关说明。

tls证书的含义如上解释，如有问题可以另外提问，感谢～
