### ISSUE TITLE
请求解密文件密钥时失败

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/trustedflow#38]
### Issue Type

Build/Install

### Source

binary

### Capsule Manager Version

0.2.0b0

### Capsule Manager SDK Version

0.2.0b0

### Tee Apps Version

0.2.0b0

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.10

### What happend and What you expected to happen.

```shell
大佬，您好！我在最后一步从alice请求解密结果的密钥时失败。
    raise CapsuleManagerError(
sdc.error.CapsuleManagerError: CapsuleManager server error code: 13, error message: err code: Assert err; err detail: model_uuid xgb_model is not the same as expected; location: [line = 346, file = capsule-manager/src/core/model/request.rs]
model_uuid xgb_model应该是对应的一组吧，为什么会出错呢？
```

### Reproduction code to reproduce the issue.

```shell
get_export_data_key_b64:
  # (required) str
  party_id: "XDQSXTKQC4LGD3V5LXROVB5C4THPWULM45M6DQX32SPBAE7Y66DA"
  # (required) str
  resource_uri: xgb_model
  # (required) str
  data_export_certificate_file: vote-result.json
```

**Comment by zhongtianq** [comment]
@zzx-QDU 你好，resource_uri请使用model_uuid，与导出申请的时候以及与计算的时候保持一致即可。可能我们的文档中的说明不够清晰，我会将这部分说明重新明确一下。感谢提问～

**Comment by zzx-QDU** [comment]
好的，感谢。此外，这一步中2.2第一句话“首先，bob需要把以下内容复制到一个空文件，假设文件叫做sign.yaml。”如果与后面步骤对应的话，应该是voter.yaml吧。
