### ISSUE TITLE
关于capsule-manager无法在sgx机器上启动的问题

### ISSUE THREAD

**Issue by Handikang** [secretflow/trustedflow#46]
我从咱们官方文档上了解到capsule-manager依赖pccs,然后pccs又依赖intel sgx sdk和sgx psw,所以我就使用官方文档中的docker命令
![image](https://github.com/secretflow/trustedflow/assets/42713276/35df051d-5e22-427e-b027-7b8146f204fc)

启动了capsule-manager，我按照流程启动不带mtls的capsule-manager的时候报了如下错误

![8a4f1572b585a8c53a2c37d5b3e4a4a](https://github.com/secretflow/trustedflow/assets/42713276/9ff79a9d-b776-4992-99df-28e3ae8ac519)

**Comment by zhongtianq** [comment]
@Handikang hi，您好。报错信息来自[occlum](https://github.com/occlum/occlum)，从报错信息看是检查 FSGSBASE 指令的支持性上宿主机有问题。当然，不排除存在其他配置问题，建议您参考[occlum](https://github.com/occlum/occlum)对主机环境验证，如有问题，麻烦您在[occlum](https://github.com/occlum/occlum)提issue解决一下。

**Comment by Handikang** [comment]
![image](https://github.com/secretflow/trustedflow/assets/42713276/945d9f99-9ea0-47c2-ab3a-f31f296ddd74)
您好，我看了下宿主机是支持这个指令的
就是比较关键的是，使用occlum run /bin/capsule_manager的时候，当下是没有/bin/capsule_manager文件的

**Comment by zhongtianq** [comment]
> ![image](https://private-user-images.githubusercontent.com/42713276/326242668-945d9f99-9ea0-47c2-ab3a-f31f296ddd74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTY0MzgsIm5iZiI6MTcxNDI5NjEzOCwicGF0aCI6Ii80MjcxMzI3Ni8zMjYyNDI2NjgtOTQ1ZDlmOTktOWVhMC00N2MyLWFiM2EtZjMxZjI5NmRkZDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA5MjIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMjlhZjIyZjA4NGM5ZWM4ZDk2YjkwY2UwMTM5ZjBhOWY2ZTlmZWNjZjExNmRmNDBmZDNjNDhkYTg5ZTAyYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1IfwDhLvzjYce0GmXq2qu6_MlVhcLsoFZRbqSC_mHNo) 您好，我看了下宿主机是支持这个指令的 就是比较关键的是，使用occlum run /bin/capsule_manager的时候，当下是没有/bin/capsule_manager文件的

occlum是一个libos，它的根目录是occlum的image目录，所以/bin/capsule_manager实际上对应的是./image/bin/capsule_manager。所以不是不存在文件导致的这个问题。

您可以运行一个最基本的occlum例子，比如hello world程序来确认一下环境。如果存在问题还请麻烦询问一下occlum团队。

**Comment by Handikang** [comment]
您好，这个问题已经解决，我就把issue关闭了
