### ISSUE TITLE
自行搭建PCCS服务那里，version、os、arch具体应该怎么填？

### ISSUE THREAD

**Issue by joaquinboss** [secretflow/trustedflow#51]
系统：ubuntu20.04
node版本：21.4（是用nvm安装的，不是根据https://github.com/nodesource/distributions安装）
问题1：https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/main/QuoteGeneration/pccs的指令"dpkg -i sgx-dcap-pccs*${version}-${os}*${arch}.deb"里面version、os、arch具体应该怎么填？
问题2：尝试跳过https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/main/QuoteGeneration/pccs的文档教程，执行命令sudo apt-get install sgx-dcap-pccs ，为何会报错？详见图片，具体是说node的实际版本为20.13，但我输入"node -v"，输出是21.4
问题3：执行命令sudo systemctl start pccs，没有任何输出，是意味着其实pccs已经搭建好了，并且也启动了吗？
![微信图片_20240510111458](https://github.com/secretflow/trustedflow/assets/74462597/a086f591-52d7-474e-9fa3-669666086551)

**Comment by zhongtianq** [comment]
这个还请麻烦在intel的相关仓库下提问哈。
