### ISSUE TITLE
数据血缘

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/trustedflow#52]
请问数据血缘如何在发挥作用？我只在文档中找到一张概念图。数据血缘会如何记录计算方执行的代码？记录会存在什么地方？

**Comment by yuki252111** [comment]
数据血缘是一张拓扑图，目前放在内存中（内存是存储的抽象层之一），如有需要（比如sql之类的存储媒介）可自行开发其他的存储层，遵循接口即可：https://github.com/secretflow/capsule-manager/blob/main/capsule-manager/src/storage/mod.rs

**Comment by yuki252111** [comment]
自然是可以的，这个是TEE的远程认证做的事情

**Comment by zzx-QDU** [comment]
也就是说授权使用5列数据，那么就必须使用5列数据吗？

**Comment by yuki252111** [comment]
远程认证可以检测运行的代码是什么，换句话说就是数据的拥有方知道自己授权的数据会被怎么进行计算。所以与使用5列还是4列没关系，只要数据拥有方认可只使用4列数据，那么就是合理的，不任何不授权即可

**Comment by zzx-QDU** [comment]
我明白您的意思。我想知道数据结果方是什么确认计算方是怎么计算的。在文档示例中，数据提供方会在计算方计算之前进行授权，并可以在计算之后解密结果。那么，数据提供方是在授权之后就百分百确定计算方会如何计算还是在解密结果时有验证计算方是否按要求计算这一步骤？

**Comment by yuki252111** [comment]
这边建议去了解一下远程认证，授权语义中有应用程序的mrenclave的纬度，这个限制死了一定是只能执行某个程序下的授权。

**Comment by zzx-QDU** [comment]
我在修改image下psi.py文件之后重新build occlum，发现度量值确实发生了变化，但是数据提供方或者结果方如何进行检查？例如，我在teeapp中修改psi.py文件对结果进行修改，结果方完全可以正常解密出修改后的psi结果。在这一过程中在结果方的视角中只有度量值发生改变，但是度量值不也是teeapp提供的，如果一开始teeapp先修改运算代码文件，然后再生成度量值，这种情况下结果方如何进行验证？

**Comment by yuki252111** [comment]
这里涉及到远程认证的过程：
1. 数据提供方本地replay获取teeapp的度量值、capsulemanager的度量值
2. 数据提供方先获取capsulemanager的远程认证报告，并把度量值与本地replay获取的比对，如果一致说明capsulemanager的代码是没有被篡改的，可以信任（因为capsulemanager的代码数据提供方都看过）
3. 数据提供方在设计授权语义的时候加入teeapp的度量值，并把授权策略上传到capsulemanager
4. capsulemanager会校验teeapp的度量值&校验是在TEE环境中，只要度量值发生变化，校验就通不过。如果不在TEE环境中校验也通不过

**Comment by zzx-QDU** [comment]
我明白了，非常感谢！
