### ISSUE TITLE
请问步骤四（仿真模式）的"检查生成的任务执行配置文件内容"是如何执行？

### ISSUE THREAD

**Issue by joaquinboss** [secretflow/trustedflow#57]
大佬们，想问下，步骤四（仿真模式）第3步的c，如何看诸如task_initiator_id、task_initiator_certs、task_body、signature的这些内容，具体是在容器teeapps-sim里的/host/integration_test的哪个文件里面可以查看到？
![微信图片_20240523104625](https://github.com/secretflow/trustedflow/assets/74462597/f1600b3d-706a-42bf-8454-b8145c8eb6c4)

**Comment by lq0404510** [comment]
如果你执行的命令是python convert.py --cert_path carol.crt --prikey_path carol.key --task_config_path psi.json --scope default --capsule_manager_endpoint {CapsuleManager的地址} --tee_task_config_path psi_task.json，可以cat psi_task.json 文件，查看生成的文件内容是否与你填充的key相符
