### ISSUE TITLE
请问步骤五，《1. 定位要导出的文件ID》哪里能看到《2. 获取数据密钥》需要用到的数据ID？

### ISSUE THREAD

**Issue by joaquinboss** [secretflow/trustedflow#58]
![微信图片_20240523161313](https://github.com/secretflow/trustedflow/assets/74462597/07c38fa3-6c2f-4f76-acaf-8f01292ee5ef)
容器（teeapps-sim）终端处的/host/testdata/breast_cancer/xgb_model文件是乱码文件，应该是加密后的文件。
/host/integration_test/xgb.json文件里面，并没有看到什么ID
请问大佬们，这个问题应该如何找到数据ID？

**Comment by lq0404510** [comment]
可以再阅读下https://www.secretflow.org.cn/zh-CN/docs/trustedflow/0.2.0b0.post0/quick_start/step5#id
【**定位要导出的文件ID那一步---- 如下所示，file://output/?id=model_uuid&&uri=/host/testdata/breast_cancer/xgb_model说明XGBoost训练APP得到的模型ID叫做model_uuid，文件位置为/host/testdata/breast_cancer/xgb_model】**

cat xgb.json | grep output_uris -A 3 -B 2
