### ISSUE TITLE
请问步骤五的2.4第一条指令，为什么会出现以下报错？

### ISSUE THREAD

**Issue by joaquinboss** [secretflow/trustedflow#59]
执行了以下这条指令后
![微信图片_20240523185730](https://github.com/secretflow/trustedflow/assets/74462597/3c36c03b-9c0f-4c43-a6d5-47c44fc6cd43)
为什么会出现以下报错？
![微信图片_20240523185906](https://github.com/secretflow/trustedflow/assets/74462597/3fa8d80c-d8c7-4b4b-bc83-17fbb2574b04)
自我感觉alice.yaml文件都没有错误，格式都是和文档对齐的，以下是alice.yaml文件的内容
![微信图片_20240523190027](https://github.com/secretflow/trustedflow/assets/74462597/771327a2-2d32-4e05-aeb1-2a2173fcc22b)
![微信图片_20240523190031](https://github.com/secretflow/trustedflow/assets/74462597/a30ca885-f6da-437f-b5de-b53eba55856d)
![微信图片_20240523190034](https://github.com/secretflow/trustedflow/assets/74462597/a912dbaa-4a31-4498-a4da-8034ab0e5fb1)
麻烦大佬们帮我看下是什么问题，应该如何解决，感激不尽！

**Comment by lq0404510** [comment]
signed-voter.yaml、voter.yaml这些文件的信息麻烦发一下看看

**Comment by joaquinboss** [comment]
> signed-voter.yaml、voter.yaml这些文件的信息麻烦发一下看看
![微信图片_20240524150818](https://github.com/secretflow/trustedflow/assets/74462597/ec526636-1297-446a-b4b0-584947d12f6b)
麻烦大佬们帮忙看下！

**Comment by lq0404510** [comment]
看下approved_action:的值 :cat vote-request.yaml | grep approved_action
alice.yaml中的resource_uri: xgb_model是跟上面的一致吗？

**Comment by joaquinboss** [comment]
> 看下approved_action:的值 :cat vote-request.yaml | grep approved_action alice.yaml中的resource_uri: xgb_model是跟上面的一致吗？
都是“model_uuid”，不是xgb_model，是要改成“file://output/?id=model_uuid&&uri=/host/testdata/breast_cancer/xgb_model”才对吗？

**Comment by lq0404510** [comment]
如果你全部按照文档步骤输出的是：file://output/?id=model_uuid&&uri=/host/testdata/breast_cancer/xgb_model”，
vote-request.yaml文件中 approved_action: "tee/download,model_uuid" 值应该是这样的
alice.yaml文件中的
get_export_data_key_b64:
  party_id: alice_party_id
  resource_uri: **model_uuid**
  data_export_certificate_file: vote-result.json 值是这样的，请检查下

**Comment by joaquinboss** [comment]
> 看下approved_action:的值 :cat vote-request.yaml | grep approved_action alice.yaml中的resource_uri: xgb_model是跟上面的一致吗？

![微信图片_20240524165729](https://github.com/secretflow/trustedflow/assets/74462597/d6b17adc-d258-4e37-bedf-3a0a801749f7)

**Comment by joaquinboss** [comment]
> 如果你全部按照文档步骤输出的是：file://output/?id=model_uuid&&uri=/host/testdata/breast_cancer/xgb_model”， vote-request.yaml文件中 approved_action: "tee/download,model_uuid" 值应该是这样的 alice.yaml文件中的 get_export_data_key_b64: party_id: alice_party_id resource_uri: **model_uuid** data_export_certificate_file: vote-result.json 值是这样的，请检查下

是的 大佬，都是写的“model_uuid”

**Comment by lq0404510** [comment]
> > 若有改动上面的配置，请从2.1 alice发起导出数据投票请求并签名 重新上传下配置，若有问题再贴下最新的报错信息

**Comment by joaquinboss** [comment]
大佬们，可以帮我看下文档里面的这个操作流程有没有问题吗？走的是仿真模式，不用开启mTLS
[TrustedFlow步骤.txt](https://github.com/secretflow/trustedflow/files/15448077/TrustedFlow.txt)

**Comment by lq0404510** [comment]
capsule-manager的日志麻烦发一下

**Comment by joaquinboss** [comment]
> capsule-manager的日志麻烦发一下

这是（capsule-manager-sim）终端的输出日志
![2024-05-27 09-54-44屏幕截图](https://github.com/secretflow/trustedflow/assets/74462597/a3847508-9314-45cc-b817-4026e6cb1883)

**Comment by zheyang0825** [comment]
> > capsule-manager的日志麻烦发一下
> 
> 这是（capsule-manager-sim）终端的输出日志 ![2024-05-27 09-54-44屏幕截图](https://private-user-images.githubusercontent.com/74462597/333935267-a3847508-9314-45cc-b817-4026e6cb1883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NzY1NTMsIm5iZiI6MTcxNjc3NjI1MywicGF0aCI6Ii83NDQ2MjU5Ny8zMzM5MzUyNjctYTM4NDc1MDgtOTMxNC00NWNjLWI4MTctNDAyNmU2Y2IxODgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAyMTczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliOTBkNGFhYjU1ZTE1M2Y1Zjk3N2I5MmJiMGRiNDUzZjQ2NjU5ZDFiZTMzZDkzMjUzOTJlYjc1ZWQzZjZkMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zK07pPJ3R09gsv-6RnD56fU3jJc4oYDOsUrKViF5rTk)

从日志看是 vote_result.json 上配置的 cert_chain 字段有问题，可以直接把这个文件内容贴一下吗？

**Comment by joaquinboss** [comment]
> > > capsule-manager的日志麻烦发一下
> > 
> > 
> > 这是（capsule-manager-sim）终端的输出日志 ![2024-05-27 09-54-44屏幕截图](https://private-user-images.githubusercontent.com/74462597/333935267-a3847508-9314-45cc-b817-4026e6cb1883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NzY1NTMsIm5iZiI6MTcxNjc3NjI1MywicGF0aCI6Ii83NDQ2MjU5Ny8zMzM5MzUyNjctYTM4NDc1MDgtOTMxNC00NWNjLWI4MTctNDAyNmU2Y2IxODgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAyMTczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliOTBkNGFhYjU1ZTE1M2Y1Zjk3N2I5MmJiMGRiNDUzZjQ2NjU5ZDFiZTMzZDkzMjUzOTJlYjc1ZWQzZjZkMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zK07pPJ3R09gsv-6RnD56fU3jJc4oYDOsUrKViF5rTk)
> 
> 从日志看是 vote_result.json 上配置的 cert_chain 字段有问题，可以直接把这个文件内容贴一下吗？

如下，截图和源文件都有，麻烦大佬看下
![微信图片_20240527102943](https://github.com/secretflow/trustedflow/assets/74462597/6ae94de7-3a65-42c1-9ba5-c56cca999871)
[vote-result.json](https://github.com/secretflow/trustedflow/files/15450165/vote-result.json)

**Comment by joaquinboss** [comment]
> 大佬们，可以帮我看下文档里面的这个操作流程有没有问题吗？走的是仿真模式，不用开启mTLS [TrustedFlow步骤.txt](https://github.com/secretflow/trustedflow/files/15448077/TrustedFlow.txt)

我按照隐语的trustedflow文档走了三遍仿真模式流程，都是在步骤五的倒数第二条指令得到了一模一样的报错。整个流程和这个txt文件严格一致的，大佬们可以看下是否我中间有不恰当的步骤

**Comment by zhongtianq** [comment]
@joaquinboss 麻烦再提供一下signed-vote-request.yaml的内容

**Comment by zhongtianq** [comment]
@joaquinboss 另外，看起来您的alice.crt和bob.crt的长度不一致，请问您的证书是用相同方式生成的吗？中间有过其他什么替换或者编辑操作么

**Comment by joaquinboss** [comment]
> @joaquinboss 麻烦再提供一下signed-vote-request.yaml的内容

如下
![微信图片_20240527105753](https://github.com/secretflow/trustedflow/assets/74462597/58c44bc7-c8b2-4cc2-9fdf-1ac3785dc8f5)
源文件受github限制，无法上传

**Comment by joaquinboss** [comment]
> @joaquinboss 另外，看起来您的alice.crt和bob.crt的长度不一致，请问您的证书是用相同方式生成的吗？中间有过其他什么替换或者编辑操作么

alice和bob的crt证书都是相同方式生成的呀，没有任何替换。
![微信图片_20240527110312](https://github.com/secretflow/trustedflow/assets/74462597/40b5a303-8df8-4735-a78e-a6e0de45e017)
倒是alice和bob的yaml文件的内容修改，我都是在宿主机，也就是外部终端用vim指令修改，改完再传回容器（capsule-manager-sdk终端）

**Comment by zhongtianq** [comment]
@joaquinboss 可以先手动清除一下vote-result.json中-----END CERTIFICATE-----\n前面的空格试试看，这个问题大概是pem证书中的空格导致的，我之后再排查一下这个格式问题出现的原因。

**Comment by joaquinboss** [comment]
> @joaquinboss 可以先手动清除一下vote-result.json中-----END CERTIFICATE-----\n前面的空格试试看，这个问题大概是pem证书中的空格导致的，我之后再排查一下这个格式问题出现的原因。

可以的，成功执行了，感谢大佬！

**Comment by zhongtianq** [comment]
为避免类似的证书格式的问题，对sdk的yaml写入方式做了更改。可见https://github.com/secretflow/capsule-manager-sdk/pull/21

pypi包已发dev.20240527，可以重新安装一下最新版本的sdk尝试一下。
