### ISSUE TITLE
请问可信APP里面拥有的Alice(Bob)的私钥是本来就存在的吗？

### ISSUE THREAD

**Issue by joaquinboss** [secretflow/trustedflow#64]
https://www.secretflow.org.cn/zh-CN/docs/trustedflow/0.2.0b0.post0/architecture/principle
如题，链接里第6步，CapsuleManager向可信APP发送（Alice的）经加密后的数据密钥，然而第7步，可信APP却直接使用（Alice的）私钥解密得到数据密钥，再用数据密钥解密得到（Alice的）原始数据。
不太理解，可信APP里面拥有的Alice的私钥是怎么来的？是可信APP里本来就存在的？还是我忽略了某些步骤（Alice向可信APP发送自己的私钥）？
大佬们可以帮忙看下这个问题吗？感激不尽！

**Comment by joaquinboss** [comment]
![微信图片_20240606114013](https://github.com/secretflow/trustedflow/assets/74462597/ffb25698-df30-4a2f-8c8c-71e2be4e6a98)

**Comment by tpppppub** [comment]
第 6 步 CapsuleManager 使用 **可信 APP 的** 公钥加密数据密钥，第 7 步可信 APP 使用的是自己的私钥解密，不是 Alice 的私钥

**Comment by joaquinboss** [comment]
> 第 6 步 CapsuleManager 使用 **可信 APP 的** 公钥加密数据密钥，第 7 步可信 APP 使用的是自己的私钥解密，不是 Alice 的私钥

可是官网上，第6步里面，CapsuleManager向可信APP发送的难道不是（Alice的）经加密后的数据密钥吗？我也没看到有和可信APP相关的公私钥
![微信图片_20240606144425](https://github.com/secretflow/trustedflow/assets/74462597/80e2d0dc-7d3e-4712-a4e9-4414c1a1d23f)

**Comment by tpppppub** [comment]
“数据密钥”是 Alice/Bob 的，加密“数据密钥”的公钥是可信应用产生的，这个公钥会附在远程认证报告里，CapsuleManager 验证完后可以使用这个公钥加密数据密钥
