### ISSUE TITLE
烦请大佬们修复一下TrustedFlow镜像源

### ISSUE THREAD

**Issue by joaquinboss** [secretflow/trustedflow#65]
在不同机器的ubuntu系统上执行“运行CapsuleManager镜像”
`docker run -it --name capsule-manager-sim --network=host secretflow/capsule-manager-sim-ubuntu22.04:latest bash`
都得到了类似的拉取镜像超时的报错
`Unable to find image 'secretflow/capsule-manager-sim-ubuntu22.04:latest' locally
latest: Pulling from secretflow/capsule-manager-sim-ubuntu22.04
bccd10f490ab: Pulling fs layer 
c68f04c398f6: Pulling fs layer 
acb65ff94393: Pulling fs layer 
8d09dc8ec270: Waiting 
3719b991c0c3: Waiting 
4406b88d1f00: Waiting 
6eb736a9844f: Waiting 
66c5dc6034a8: Waiting 
dc4f537cc51c: Waiting 
537beec93efc: Waiting 
8915fc22d7d8: Waiting 
a07e06ffa612: Waiting 
4f4fb700ef54: Waiting 
docker: error pulling image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/d8/d812e80bd13dea5b0a9a825c7ab322755c2787bcfd3523bf88081bd6646dc249/data?verify=1717728015-maQVvUPhj5j%2FMjxeG71iZS4v3Es%3D": dial tcp 157.240.2.50:443: connect: connection refused.`
麻烦大佬们去贵司隐语看下是否TrustedFlow镜像源出问题

**Comment by kaixin-haha** [comment]
好的，我们去确认下相关情况

**Comment by zhongtianq** [comment]
镜像源没有问题，请检查一下自身机器网络环境吧。

**Comment by kaixin-haha** [comment]
![image](https://github.com/secretflow/trustedflow/assets/171303223/bb2f826d-8561-4277-a16d-ef0768f37df7)
@joaquinboss 尝试了下，我们这边是可以拉取到的

**Comment by joaquinboss** [comment]
> ![image](https://private-user-images.githubusercontent.com/171303223/337511237-bb2f826d-8561-4277-a16d-ef0768f37df7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzEyMTcsIm5iZiI6MTcxNzczMDkxNywicGF0aCI6Ii8xNzEzMDMyMjMvMzM3NTExMjM3LWJiMmY4MjZkLTg1NjEtNDI3Ny1hMTZkLWVmMDc2OGYzN2RmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QwMzI4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGMyZjkyNmY5MzA4MGQwODdjN2MyNzU3NGIxOWY5ZmRhZjdiNTFjNmZmODk0ZTQzNGNlNWM3OTJmMmUyYTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZeQIDiCCIck8BnUtIyEekXkX1Ez3JelQ8cImaBMtRMQ) @joaquinboss 尝试了下，我们这边是可以拉取到的

那就奇怪了，我换了网络环境，在不同ubuntu机器上执行都还是不行，也是类似的超时报错

**Comment by zimu-yuxi** [comment]
@joaquinboss hi，试一下下面命令呢
docker pull secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/capsule-manager-sim-ubuntu22.0.4:latest

**Comment by joaquinboss** [comment]
> @joaquinboss hi，试一下下面命令呢 docker pull secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/capsule-manager-sim-ubuntu22.0.4:latest

好的哈，感谢大佬
已经把镜像传到阿里云了

**Comment by zhouaihui** [comment]
由于某些不可抗拒原因，国内访问docker hub等服务受限，后续TrustedFlow会提供国内源。

**Comment by joaquinboss** [comment]
确实是不可抗拒，已自行把贵司的docker镜像挂到阿里云了
