### ISSUE TITLE
请问carol的机构ID为什么不可以在teeappss-sim容器终端生成？

### ISSUE THREAD

**Issue by joaquinboss** [secretflow/trustedflow#70]
大佬们，carol的机构ID理应是要在哪里生成的？
![微信图片_20240614180644](https://github.com/secretflow/trustedflow/assets/74462597/61a371cb-3840-4587-87f4-1a4d3c4f84b5)

我在teeappss-sim容器终端执行`cms_util generate-party-id --cert-file carol.crt`，但是没有对应的命令
请问理应是要在capsule-manager-sdk容器终端生成吗？

**Comment by lq0404510** [comment]
carol是跟bob和alice一样的方式，要在capsule-manager-sdk里去执行的cms_util generate-party-id --cert-file carol.crt此命令去生成party_id，还要确保当前目录存在carol.crt证书，

**Comment by joaquinboss** [comment]
可是trustedflow例程里面，不是默认carol是TEE机器（可信APP）的使用者吗？
我的理解是alice和bob操控的容器终端是capsule-manager-sdk，而carol操控的容器终端是teeapps-sim
那么carol的机构ID由carol这个使用者在teeapps-sim里面执行`cms_util generate-party-id --cert-file carol.crt`去生成不是更合理吗？
carol.key和carol.crt我是可以能在teeapps-sim里面执行指令生成的
麻烦 大佬再帮我捋一下我的理解是否正确

**Comment by zhouaihui** [comment]
你的理解是对的。

教程只是一个演示示例，可能是你一个人充当了多个机构的角色，所以在哪里执行可能没有那么严格，只要你能拿到就行。实际运作中，机构的私钥肯定是机构内部才可见，机构ID是需要机构自己给出的。

**Comment by joaquinboss** [comment]
> 你的理解是对的。
> 
> 教程只是一个演示示例，可能是你一个人充当了多个机构的角色，所以在哪里执行可能没有那么严格，只要你能拿到就行。实际运作中，机构的私钥肯定是机构内部才可见，机构ID是需要机构自己给出的。

好的，感谢周老师
